import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { PolicyGenContextProvider } from "@/context/policyGenerator";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "AIPolicyPro",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  }
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth();

  return (
    <html lang="en">
      <body
        className={`${poppins.className} dark`}
      >
        <SessionProvider session={session}>
          <PolicyGenContextProvider>
            {children}
          </PolicyGenContextProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
